# Generated by Django 4.1.1 on 2022-09-20 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diamantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_diamantes', models.IntegerField()),
                ('name_diamantes', models.CharField(max_length=200)),
                ('price_diamantes', models.IntegerField(max_length=200)),
            ],
        ),
    ]
