# Generated by Django 4.1.1 on 2022-09-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recargas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diamantes',
            name='price_diamantes',
            field=models.CharField(max_length=200),
        ),
    ]
