# Generated by Django 4.1.1 on 2022-09-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recargas', '0002_alter_diamantes_price_diamantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=200)),
                ('number_card', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('code_cv', models.CharField(max_length=4)),
            ],
        ),
    ]
