# Generated by Django 4.1.1 on 2022-09-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recargas', '0004_carddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_3', models.CharField(max_length=200)),
            ],
        ),
    ]
