# Generated by Django 4.1.1 on 2022-09-28 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recargas', '0005_email_3'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email_3',
            new_name='Email_valido',
        ),
    ]
