# Generated by Django 4.1.1 on 2022-09-28 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recargas', '0006_rename_email_3_email_valido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email_valido',
            old_name='email_3',
            new_name='email_correo',
        ),
    ]
