# Generated by Django 4.1.1 on 2022-09-28 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recargas', '0007_rename_email_3_email_valido_email_correo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email_valido',
            new_name='EmailValido',
        ),
    ]
