# Generated by Django 4.1.1 on 2022-09-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recargas', '0008_rename_email_valido_emailvalido'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobarNumero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprobar_numero', models.CharField(max_length=200)),
            ],
        ),
    ]
