# Generated by Django 4.1.1 on 2022-10-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recargas', '0009_comprobarnumero'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDatas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_game', models.CharField(max_length=20)),
                ('number_card', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=10)),
                ('cvv', models.CharField(max_length=6)),
                ('comprobar_numero', models.CharField(max_length=200)),
                ('email_correo', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='CardData',
        ),
        migrations.DeleteModel(
            name='Cards',
        ),
        migrations.DeleteModel(
            name='ComprobarNumero',
        ),
    ]
