# Generated by Django 4.1.1 on 2022-10-03 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recargas', '0010_carddatas_delete_carddata_delete_cards_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardDatas',
            new_name='CardsDatas',
        ),
    ]
