# Generated by Django 4.1.1 on 2022-10-03 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recargas', '0011_rename_carddatas_cardsdatas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardsdatas',
            name='email_correo',
        ),
    ]
